-- Supabase schema for Mannequin Care admin features
-- Generated by Zencoder on 2025-11-10

-- Extensions
create extension if not exists "pgcrypto";

-- Helper function for updated_at
create or replace function public.set_updated_at()
returns trigger as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$ language plpgsql;

-- Enums
create type public.user_role as enum ('customer', 'staff', 'admin');
create type public.product_status as enum ('draft', 'active', 'archived');
create type public.blog_status as enum ('draft', 'scheduled', 'published');
create type public.review_status as enum ('pending', 'approved', 'rejected');
create type public.order_status as enum ('pending', 'processing', 'completed', 'cancelled', 'refunded');
create type public.payment_status as enum ('pending', 'authorized', 'paid', 'failed', 'refunded');
create type public.address_type as enum ('billing', 'shipping');

-- Profiles table (extends auth.users)
create table if not exists public.profiles (
  id uuid primary key references auth.users on delete cascade,
  display_name text,
  role public.user_role not null default 'customer',
  avatar_url text,
  phone text,
  metadata jsonb default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create trigger update_profiles_updated_at
  before update on public.profiles
  for each row
  execute function public.set_updated_at();

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, display_name, role, metadata)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'full_name', new.email),
    coalesce((coalesce(new.raw_user_meta_data, '{}'::jsonb)->>'role')::public.user_role, 'customer'),
    jsonb_build_object('email', new.email)
    || case
         when coalesce(new.raw_user_meta_data, '{}'::jsonb) ? 'role'
         then jsonb_build_object('role', coalesce(new.raw_user_meta_data, '{}'::jsonb)->>'role')
         else '{}'::jsonb
       end
  )
  on conflict (id) do update
    set display_name = excluded.display_name,
        role = excluded.role,
        metadata = public.profiles.metadata || excluded.metadata;
  return new;
end;
$$;

create or replace function public.handle_user_update()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.profiles
    set
      display_name = coalesce(new.raw_user_meta_data->>'full_name', new.email, display_name),
      role = coalesce((coalesce(new.raw_user_meta_data, '{}'::jsonb)->>'role')::public.user_role, role),
      metadata =
        coalesce(metadata, '{}'::jsonb)
        || jsonb_build_object('email', new.email)
        || case
             when coalesce(new.raw_user_meta_data, '{}'::jsonb) ? 'role'
             then jsonb_build_object('role', coalesce(new.raw_user_meta_data, '{}'::jsonb)->>'role')
             else '{}'::jsonb
           end,
      updated_at = timezone('utc', now())
  where id = new.id;
  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

create trigger on_auth_user_updated
  after update on auth.users
  for each row execute function public.handle_user_update();

-- User addresses
create table if not exists public.user_addresses (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  type public.address_type not null,
  full_name text not null,
  phone text not null,
  street_address text not null,
  city text not null,
  state text not null,
  postal_code text not null,
  country text not null default 'India',
  is_default boolean not null default false,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create trigger update_user_addresses_updated_at
  before update on public.user_addresses
  for each row
  execute function public.set_updated_at();

-- Categories (supports main/sub via parent_id)
create table if not exists public.product_categories (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  slug text not null unique,
  description text,
  parent_id uuid references public.product_categories on delete cascade,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create trigger update_product_categories_updated_at
  before update on public.product_categories
  for each row
  execute function public.set_updated_at();

-- Products
create table if not exists public.products (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  slug text not null unique,
  description text,
  sku text,
  price numeric(10,2) not null,
  compare_at_price numeric(10,2),
  stock integer not null default 0,
  main_category_id uuid references public.product_categories(id) on delete set null,
  sub_category_id uuid references public.product_categories(id) on delete set null,
  status public.product_status not null default 'draft',
  is_featured boolean not null default false,
  thumbnail_url text,
  metadata jsonb default '{}'::jsonb,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create trigger update_products_updated_at
  before update on public.products
  for each row
  execute function public.set_updated_at();

-- Product media gallery
create table if not exists public.product_media (
  id uuid primary key default gen_random_uuid(),
  product_id uuid not null references public.products(id) on delete cascade,
  url text not null,
  alt_text text,
  sort_order integer not null default 0,
  created_at timestamptz not null default timezone('utc', now())
);

-- Orders
create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  order_number text not null unique,
  user_id uuid references public.profiles(id) on delete set null,
  status public.order_status not null default 'pending',
  payment_status public.payment_status not null default 'pending',
  subtotal numeric(10,2) not null default 0,
  discount_total numeric(10,2) not null default 0,
  tax_total numeric(10,2) not null default 0,
  shipping_total numeric(10,2) not null default 0,
  grand_total numeric(10,2) not null default 0,
  currency char(3) not null default 'INR',
  payment_provider text,
  billing_address jsonb,
  shipping_address jsonb,
  notes text,
  placed_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create trigger update_orders_updated_at
  before update on public.orders
  for each row
  execute function public.set_updated_at();

-- Order items
create table if not exists public.order_items (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete cascade,
  product_id uuid references public.products(id) on delete set null,
  quantity integer not null check (quantity > 0),
  unit_price numeric(10,2) not null,
  line_total numeric(10,2) not null,
  product_snapshot jsonb
);

-- Blogs
create table if not exists public.blog_posts (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  slug text not null unique,
  excerpt text,
  content text,
  cover_image_url text,
  status public.blog_status not null default 'draft',
  published_at timestamptz,
  author_id uuid references public.profiles(id) on delete set null,
  tags text[] default '{}',
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create trigger update_blog_posts_updated_at
  before update on public.blog_posts
  for each row
  execute function public.set_updated_at();

-- Reviews
create table if not exists public.product_reviews (
  id uuid primary key default gen_random_uuid(),
  product_id uuid not null references public.products(id) on delete cascade,
  user_id uuid references public.profiles(id) on delete set null,
  rating smallint not null check (rating between 1 and 5),
  title text,
  body text,
  status public.review_status not null default 'pending',
  admin_response text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create trigger update_product_reviews_updated_at
  before update on public.product_reviews
  for each row
  execute function public.set_updated_at();

-- Settings key/value store
create table if not exists public.site_settings (
  id uuid primary key default gen_random_uuid(),
  key text not null unique,
  value jsonb not null,
  description text,
  updated_at timestamptz not null default timezone('utc', now())
);

-- Cart & wishlist (used by header counts)
create table if not exists public.cart_items (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  product_id uuid not null references public.products(id) on delete cascade,
  quantity integer not null check (quantity > 0),
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.wishlist_items (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  product_id uuid not null references public.products(id) on delete cascade,
  created_at timestamptz not null default timezone('utc', now()),
  unique (user_id, product_id)
);

-- Helper function for updated_at
create or replace function public.set_updated_at()
returns trigger as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$ language plpgsql;

create or replace function public.is_admin()
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  current_role public.user_role;
begin
  if auth.uid() is null then
    return false;
  end if;

  select role
    into current_role
  from public.profiles
  where id = auth.uid();

  return current_role in ('admin', 'staff');
exception
  when others then
    return false;
end;
$$;

-- Row level security
alter table public.profiles enable row level security;
alter table public.user_addresses enable row level security;
alter table public.product_categories enable row level security;
alter table public.products enable row level security;
alter table public.product_media enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.blog_posts enable row level security;
alter table public.product_reviews enable row level security;
alter table public.site_settings enable row level security;
alter table public.cart_items enable row level security;
alter table public.wishlist_items enable row level security;

-- Profiles policies
create policy "Profiles are viewable by owner or admins" on public.profiles
  for select using (
    auth.uid() = id or
    public.is_admin()
  );

create policy "Users can update own profile" on public.profiles
  for update using (auth.uid() = id);

create policy "Admins manage profiles" on public.profiles
  for all using (public.is_admin());

-- User addresses policies
create policy "Users can manage own addresses" on public.user_addresses
  for all using (auth.uid() = user_id);

create policy "Admins can view all addresses" on public.user_addresses
  for select using (public.is_admin());

-- Admin-only policies (products, categories, etc.)
create policy "Admins manage categories" on public.product_categories
  for all using (public.is_admin());

create policy "Public can view categories" on public.product_categories
  for select using (true);

create policy "Admins manage products" on public.products
  for all using (public.is_admin());

create policy "Public can view active products" on public.products
  for select using (status = 'active');

create policy "Admins manage product media" on public.product_media
  for all using (public.is_admin());

create policy "Public can view product media" on public.product_media
  for select using (true);

create policy "Admins manage orders" on public.orders
  for all using (public.is_admin());

create policy "Admins manage order items" on public.order_items
  for all using (public.is_admin());

create policy "Admins manage blogs" on public.blog_posts
  for all using (public.is_admin());

create policy "Admins manage reviews" on public.product_reviews
  for all using (public.is_admin());

create policy "Public can view approved reviews" on public.product_reviews
  for select using (status = 'approved');

create policy "Customers can view own reviews" on public.product_reviews
  for select using (auth.uid() = user_id);

create policy "Admins manage settings" on public.site_settings
  for all using (public.is_admin());

-- Customer access for orders, reviews, cart, wishlist
create policy "Customers select own orders" on public.orders
  for select using (auth.uid() = user_id);

create policy "Customers select own order items" on public.order_items
  for select using (
    exists (
      select 1 from public.orders o
      where o.id = order_items.order_id and o.user_id = auth.uid()
    )
  );

create policy "Customers manage own reviews" on public.product_reviews
  for all using (auth.uid() = user_id);

create policy "Customers can insert reviews" on public.product_reviews
  for insert with check (auth.uid() = user_id);

create policy "Customers manage cart" on public.cart_items
  for all using (auth.uid() = user_id);

create policy "Customers manage wishlist" on public.wishlist_items
  for all using (auth.uid() = user_id);

-- Useful indexes
create index if not exists idx_user_addresses_user on public.user_addresses(user_id);
create index if not exists idx_user_addresses_type on public.user_addresses(user_id, type);
create unique index if not exists idx_user_addresses_default on public.user_addresses(user_id, type) where is_default = true;
create index if not exists idx_product_categories_parent on public.product_categories(parent_id);
create index if not exists idx_products_main_category on public.products(main_category_id);
create index if not exists idx_products_sub_category on public.products(sub_category_id);
create index if not exists idx_products_status on public.products(status);
create index if not exists idx_orders_user on public.orders(user_id);
create index if not exists idx_blog_posts_status on public.blog_posts(status);
create index if not exists idx_reviews_product on public.product_reviews(product_id);

-- Stock decrement helper (called server-side after order creation)
create or replace function public.decrement_stock(p_product_id uuid, p_quantity integer)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.products
    set stock = greatest(0, stock - p_quantity)
  where id = p_product_id;
end;
$$;

-- RLS: allow authenticated customers to insert their own orders
create policy "Customers can place orders" on public.orders
  for insert with check (auth.uid() = user_id or user_id is null);

-- RLS: allow authenticated customers to insert their own order items
create policy "Customers can insert order items" on public.order_items
  for insert with check (
    exists (
      select 1 from public.orders o
      where o.id = order_items.order_id
        and (o.user_id = auth.uid() or o.user_id is null)
    )
  );
